### ISSUE TITLE
Missing small character "ə" (uni0259)

### ISSUE THREAD

**Issue by DrELM** [googlefonts/roboto#249]
I found your font - Roboto - very useful especially with extended character set. However, there is keystone character - ə (Uni0259, #601;) which is not added to Latin-extended set. This is the only missing character that can be in almost every word of the text written in Azerbaijan language. In fact, there is very similar ready glyph which can be found in your font cyrillic set - ә (Uni04D9, #1241;). 

It is very important for our national webdevelopers to use this font in our own language as Google Webfont. 

I kindly request you to copy Unicode 04D9 character to 0259 and update the font in Google Fonts.

**Comment by davelab6** [comment]
@DrELM thanks for reporting

**Comment by codeman38** [comment]
U+0259 is definitely present in the binaries from this repo - probably an issue in Google Fonts subsetting?

**Comment by m4rc1e** [comment]
@codeman38 You're correct. Roboto Webfonts include U+0259 https://github.com/google/roboto/blob/master/res/charsets/web.txt#L341

![screen shot 2017-08-11 at 15 34 53](https://user-images.githubusercontent.com/7525512/29217794-aa649cb0-7eaa-11e7-80df-5e2f92de8ee7.png)

I've made up a quick JsBin test: http://jsbin.com/vawocihoyi/edit?html,css,output

Output in test is not Roboto.
