### ISSUE TITLE
Character: Ə

### ISSUE THREAD

**Issue by nicatmanaf** [googlefonts/roboto#293]
Roboto missing character Ə ə

**Comment by EwonRael** [comment]
I think this is a repeat of https://github.com/google/roboto/issues/249

**Comment by GasimGasimzada** [comment]
@EwonRael I am currently testing Roboto in one of our projects by loading it through Google Fonts:

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,700&amp;subset=latin-ext" rel="stylesheet">

For some reason, when testing the website on Windows 10 running Firefox, Chrome, or Edge, the fonts are misplaced:

<img width="213" alt="Screen Shot 2019-03-26 at 3 11 40 AM" src="https://user-images.githubusercontent.com/807231/54960154-f400bb00-4f74-11e9-8b20-28d665195758.png">

<img width="427" alt="Screen Shot 2019-03-26 at 3 10 33 AM" src="https://user-images.githubusercontent.com/807231/54960158-f95e0580-4f74-11e9-9ec4-c5e24112906f.png">

However, the fonts are displayed perfectly fine in macOS running Firefox, Chrome, or Safari. This only happens with these two letters. What can cause such an issue here?

**Comment by davelab6** [comment]
with https://jsbin.com/kupebuz/edit?html,output i can not reproduce this, so closing
