### ISSUE TITLE
Incorrect "»" in Roboto Light

### ISSUE THREAD

**Issue by mittus** [googlefonts/roboto#294]
I use Roboto Light (300). 

On the page https://fonts.google.com/specimen/Roboto?subset=cyrillic&selection.family=Roboto:300,400,500,700 I see normal text, but when I use it from `@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Condensed:400&subset=cyrillic');`, I see incorrect symbol:

![test3](https://user-images.githubusercontent.com/711179/43883894-d99c8272-9bb4-11e8-84f3-5411c32c6100.png)
![test2](https://user-images.githubusercontent.com/711179/43883871-c4613fba-9bb4-11e8-9181-76b2f86d1702.png)

**Comment by m4rc1e** [comment]
Here's a [jsbin](https://jsbin.com/fufodutonu/1/edit?html,output)

I see no issue on OS X Chrome 67 and Safari 11.1.2

![screen shot 2018-08-09 at 08 59 24](https://user-images.githubusercontent.com/7525512/43886065-8c3705fe-9bb2-11e8-85ff-8b0587eea52a.png)

Is Roboto installed locally on your machine? if so, remove it.

**Comment by mittus** [comment]
It's work for me. Sorry for issue

**Comment by fitojb** [comment]
You have a very old version installed locally, and it’s conflicting with the browser.

**Comment by VladWinner** [comment]
> It's work for me. Sorry for issue

Then you should close your issue.
